#!/usr/bin/env node

import express from "express";
import path from "path";

const app = express();
const __dirname = new URL('.', import.meta.url).pathname;

// 🔑 REQUIRED for SharedArrayBuffer
app.use((req, res, next) => {
  res.setHeader("Cross-Origin-Opener-Policy", "same-origin");
  res.setHeader("Cross-Origin-Embedder-Policy", "require-corp");
  next();
});

// Serve static files (your app)
app.use(express.static(__dirname));

app.listen(8080, () => {
  console.log("Server running at http://localhost:8080");
});

